import itertools
from typing import Tuple

import numpy as np
from vtkmodules import all as vtk
from vtkmodules.util.numpy_support import vtk_to_numpy
from vtkmodules.vtkCommonCore import vtkLookupTable, vtkPoints
from vtkmodules.vtkCommonDataModel import vtkPolyData
from vtkmodules.vtkFiltersCore import vtkPolyDataNormals
from vtkmodules.vtkRenderingCore import vtkActor


def _capture_actor_props(actor: vtkActor) -> dict:
    """Return a serialisable snapshot of the actor's visual properties.

    Parameters
    ----------
    actor : vtkActor
        The actor whose properties to capture.

    Returns
    -------
    dict
        A dictionary with keys ``ambient``, ``diffuse``, ``specular``,
        ``color`` (tuple of RGB), ``opacity``, and ``wireframe``.
    """
    prop = actor.GetProperty()
    return {
        "ambient": prop.GetAmbient(),
        "diffuse": prop.GetDiffuse(),
        "specular": prop.GetSpecular(),
        "color": tuple(prop.GetColor()),
        "opacity": prop.GetOpacity(),
        "wireframe": prop.GetRepresentation() == vtk.VTK_WIREFRAME,
    }


def _apply_actor_props(actor: vtkActor, props: dict) -> None:
    """Restore visual properties captured by _capture_actor_props.

    Parameters
    ----------
    actor : vtkActor
        The actor to which properties will be applied.
    props : dict
        A dictionary containing the property values as generated by
        ``_capture_actor_props``.
    """
    prop = actor.GetProperty()
    prop.SetAmbient(props["ambient"])
    prop.SetDiffuse(props["diffuse"])
    prop.SetSpecular(props["specular"])
    prop.SetColor(*props["color"])
    prop.SetOpacity(props.get("opacity", 1.0))
    if props["wireframe"]:
        prop.SetRepresentationToWireframe()
    else:
        prop.SetRepresentationToSurface()


def _make_overhang_lut(threshold_deg: float) -> vtkLookupTable:
    """Return a lookup table for overhang angles (0-180°).

    Parameters
    ----------
    threshold_deg : float
        The overhang threshold in degrees above horizontal (i.e., 90° + offset).
        Angles above this value are considered critical (red).

    Returns
    -------
    vtkLookupTable
        A lookup table that maps angles to colours:
        - green for 0–90° (safe),
        - gradient from orange to red for 90°–`threshold_deg`,
        - red for >`threshold_deg`.
    """
    lut = vtkLookupTable()
    lut.SetNumberOfTableValues(256)
    lut.SetRange(0.0, 180.0)
    for i in range(256):
        angle = (i / 255.0) * 180.0
        if angle <= 90.0:
            lut.SetTableValue(i, 0.15, 0.78, 0.15, 1.0)
        elif angle <= threshold_deg:
            t = (angle - 90.0) / max(threshold_deg - 90.0, 1e-6)
            lut.SetTableValue(i, 1.0, 0.65 * (1 - t) + 0.25 * t, 0.0, 1.0)
        else:
            lut.SetTableValue(i, 0.90, 0.12, 0.05, 1.0)
    lut.Build()
    return lut


def _make_wall_lut(min_mm: float, max_mm: float) -> vtkLookupTable:
    """Return a lookup table for wall thickness (red=thin, green=thick).

    Parameters
    ----------
    min_mm : float
        Minimum wall thickness value (mapped to red).
    max_mm : float
        Maximum wall thickness value (mapped to green).

    Returns
    -------
    vtkLookupTable
        A lookup table with a red-to-green gradient over the range
        [`min_mm`, `max_mm`].
    """
    lut = vtkLookupTable()
    lut.SetNumberOfTableValues(256)
    lut.SetRange(min_mm, max_mm)
    for i in range(256):
        t = i / 255.0
        lut.SetTableValue(i, 1.0 - t, t * 0.78, 0.05, 1.0)
    lut.Build()
    return lut


def _extract_cells_by_mask(poly_data: vtkPolyData,
                           mask: np.ndarray) -> vtkPolyData:
    """Return a new vtkPolyData containing only cells where mask is True.

    Parameters
    ----------
    poly_data : vtkPolyData
        The input polydata.
    mask : np.ndarray of bool
        A boolean array with True for cells to keep.

    Returns
    -------
    vtkPolyData
        A new polydata with the same points but only the selected cells.
    """
    new_pd = vtkPolyData()
    new_pts = vtkPoints()
    new_pts.DeepCopy(poly_data.GetPoints())
    new_pd.SetPoints(new_pts)
    new_pd.Allocate()
    for cell_id in np.where(mask)[0]:
        cell = poly_data.GetCell(int(cell_id))
        new_pd.InsertNextCell(cell.GetCellType(), cell.GetPointIds())
    new_pd.BuildLinks()
    return new_pd


def _model_base_and_height(
        bounds: tuple, build_dir: Tuple[float, float, float]
) -> Tuple[float, float]:
    """Return (base_h, height) for bounds projected along build_dir.

    Parameters
    ----------
    bounds : tuple of float
        Six-element bounds (xmin, xmax, ymin, ymax, zmin, zmax).
    build_dir : tuple of float
        Unit build direction vector.

    Returns
    -------
    (float, float)
        base_h : the minimal projection of the model corners onto the build direction.
        height : the difference between maximal and minimal projections.
    """
    b = bounds
    direction = np.asarray(build_dir, dtype=np.float64)
    direction = direction / np.linalg.norm(direction)
    corners = np.array(
        list(itertools.product([b[0], b[1]], [b[2], b[3]], [b[4], b[5]]))
    )
    projections = corners @ direction
    return float(projections.min()), float(
        projections.max() - projections.min())


def _compute_cell_angles(poly_data: vtkPolyData,
                         build_dir: Tuple[float, float, float]
                         ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compute angle (deg) between each cell normal and the build direction.

    Parameters
    ----------
    poly_data : vtkPolyData
        The input surface mesh.
    build_dir : tuple of float
        Unit build direction vector.

    Returns
    -------
    angles : ndarray of float32
        Array of angles in degrees in [0, 180].  A value of 0° means the
        face normal is parallel to the build direction (pointing straight
        up); 90° means the face is vertical; values above 90° mean the
        normal has a component *opposing* the build direction (overhanging).
    cell_normals : ndarray of float64
        Array of normal vectors for each cell.
    dots : ndarray of float64
        Clipped dot products n̂·d̂ in [-1, 1].  Negative values directly
        identify overhanging faces (dots < 0) and their magnitude indicates
        severity, avoiding the need to infer sign from angle > 90°.
    """
    nf = vtkPolyDataNormals()
    nf.SetInputData(poly_data)
    nf.ComputeCellNormalsOn()
    nf.ComputePointNormalsOff()
    nf.SplittingOff()
    nf.ConsistencyOn()
    nf.Update()
    output = nf.GetOutput()
    normals_vtk = output.GetCellData().GetNormals()
    if normals_vtk is None:
        raise RuntimeError("Could not compute cell normals.")
    cell_normals = vtk_to_numpy(normals_vtk)
    build = np.array(build_dir, dtype=np.float64)
    build /= np.linalg.norm(build)
    dots = np.clip(cell_normals @ build, -1.0, 1.0)
    angles = np.degrees(np.arccos(dots)).astype(np.float32)
    return angles, cell_normals, dots
